version: 0.2

phases:
  install:
    commands:
      - echo "install"
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - aws cloudformation create-stack --stack-name myteststack --template-body file://DynamoDB.yaml
      - aws cloudformation create-stack --stack-name myteststack --template-body file://DynamoDB1.yaml
      - aws cloudformation create-stack --stack-name myteststack --template-body file://lambda-api.yaml
artifacts:
  type: zip
  files:
    - '**/*'
